In [87]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [88]:
df = pd.read_csv('data.csv')

In [89]:
from sklearn.preprocessing import LabelEncoder
df['label'] = LabelEncoder().fit_transform(df['Area'])
df['name_lab'] = LabelEncoder().fit_transform(df['Name'])

In [90]:
data = df.drop(['Name','Area'],axis = 1)

In [91]:
from sklearn.cluster import KMeans
x_pca = PCA(n_components=2).fit_transform(data)
kmeans = KMeans(n_clusters=4, random_state = 42).fit(data)


In [92]:
kmeans.labels_[:10]

array([3, 3, 2, 2, 3, 3, 0, 0, 0, 1])

In [93]:
pd.Series(kmeans.labels_).to_csv('attempt15.csv')

In [83]:
from sklearn.preprocessing import StandardScaler

x_scale = StandardScaler().fit_transform(data)
x_pca_ss = PCA(n_components=2).fit_transform(x_scale)
SS = KMeans(n_clusters=4, random_state=42).fit(x_pca_ss)
SS.labels_[:10]

array([0, 3, 2, 1, 1, 0, 0, 0, 3, 2])

In [ ]:
x_pca = PCA(n_components=2).fit_transform(x_scale)

In [84]:
from sklearn.preprocessing import MinMaxScaler
x_min = MinMaxScaler().fit_transform(data)
x_pca_minmax = PCA(n_components=2).fit_transform(x_min)

minmax = KMeans(n_clusters=4, random_state=42).fit(x_pca_minmax)
minmax.labels_[:10]

array([2, 0, 3, 0, 0, 0, 2, 1, 2, 1])

In [86]:
pd.Series(kmeans.labels_).to_csv('attempt12kmcpa.csv')
pd.Series(SS.labels_).to_csv('attempt13sscpa.csv')
pd.Series(minmax.labels_).to_csv('attempt14mincpa.csv')